name: windows env variable test
on: push
jobs:
  Test:
    runs-on: windows-latest
    env:
      MY_VARIABLE: "default"
    steps:
      - name: set environment variable
        env:
          MY_VARIABLE: "yaml"
        run:  echo ${{ env.MY_VARIABLE }}
      - name: read environment variable
        run:  echo ${{ env.MY_VARIABLE }}
