name: windows env variable test
on: push

jobs:
  Test:
    runs-on: windows-latest
    vars:
      MY_VARIABLE: "default"
    steps:
      - name: set variable
        vars:
          MY_VARIABLE: "updated"
        run:  echo MY_VARIABLE = ${{ vars.MY_VARIABLE }}
      - name: read variable
        run:  echo MY_VARIABLE = ${{ vars.MY_VARIABLE }}
