name: windows env variable test
on: push
vars:
  MY_VARIABLE: "default"
jobs:
  Test:
    runs-on: windows-latest
    steps:
      - name: set variable
        vars:
          MY_VARIABLE: "updated"
        run:  true
      - name: read environment variable
        run:  echo MY_VARIABLE="${{ vars.MY_VARIABLE }}"
