name: windows env variable test
on:
  workflow_dispatch:
    inputs: null
jobs:
  Test:
    runs-on: windows-latest
    env:
      MY_VARIABLE: "default"
    steps:
      - name: set environment variable
        run:  echo "MY_VARIABLE=updated with spaces" >> $env:GITHUB_ENV
      - name: read environment variable
        run:  echo "${{ env.MY_VARIABLE }}"
